/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IStoryHuntV3SwapCallback } from "../IStoryHuntV3SwapCallback";

export class IStoryHuntV3SwapCallback__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStoryHuntV3SwapCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IStoryHuntV3SwapCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "amount0Delta",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "amount1Delta",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "storyHuntV3SwapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
