/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PairFlashInterface extends ethers.utils.Interface {
  functions: {
    "WIP9()": FunctionFragment;
    "factory()": FunctionFragment;
    "initFlash(tuple)": FunctionFragment;
    "refundIP()": FunctionFragment;
    "storyHuntV3FlashCallback(uint256,uint256,bytes)": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "sweepToken(address,uint256,address)": FunctionFragment;
    "unwrapWIP9(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "WIP9", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initFlash",
    values: [
      {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "refundIP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "storyHuntV3FlashCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sweepToken",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrapWIP9",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "WIP9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initFlash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refundIP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storyHuntV3FlashCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweepToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unwrapWIP9", data: BytesLike): Result;

  events: {};
}

export class PairFlash extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PairFlashInterface;

  functions: {
    WIP9(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "WIP9()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    factory(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "factory()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    initFlash(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initFlash((address,address,uint24,uint256,uint256,uint24,uint24))"(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    refundIP(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "refundIP()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

    storyHuntV3FlashCallback(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "storyHuntV3FlashCallback(uint256,uint256,bytes)"(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "swapRouter()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    sweepToken(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "sweepToken(address,uint256,address)"(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    unwrapWIP9(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "unwrapWIP9(uint256,address)"(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  WIP9(overrides?: CallOverrides): Promise<string>;

  "WIP9()"(overrides?: CallOverrides): Promise<string>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  initFlash(
    params: {
      token0: string;
      token1: string;
      fee1: BigNumberish;
      amount0: BigNumberish;
      amount1: BigNumberish;
      fee2: BigNumberish;
      fee3: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initFlash((address,address,uint24,uint256,uint256,uint24,uint24))"(
    params: {
      token0: string;
      token1: string;
      fee1: BigNumberish;
      amount0: BigNumberish;
      amount1: BigNumberish;
      fee2: BigNumberish;
      fee3: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  refundIP(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "refundIP()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  storyHuntV3FlashCallback(
    fee0: BigNumberish,
    fee1: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "storyHuntV3FlashCallback(uint256,uint256,bytes)"(
    fee0: BigNumberish,
    fee1: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  "swapRouter()"(overrides?: CallOverrides): Promise<string>;

  sweepToken(
    token: string,
    amountMinimum: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "sweepToken(address,uint256,address)"(
    token: string,
    amountMinimum: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  unwrapWIP9(
    amountMinimum: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "unwrapWIP9(uint256,address)"(
    amountMinimum: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    WIP9(overrides?: CallOverrides): Promise<string>;

    "WIP9()"(overrides?: CallOverrides): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    initFlash(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "initFlash((address,address,uint24,uint256,uint256,uint24,uint24))"(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    refundIP(overrides?: CallOverrides): Promise<void>;

    "refundIP()"(overrides?: CallOverrides): Promise<void>;

    storyHuntV3FlashCallback(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "storyHuntV3FlashCallback(uint256,uint256,bytes)"(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    "swapRouter()"(overrides?: CallOverrides): Promise<string>;

    sweepToken(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "sweepToken(address,uint256,address)"(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unwrapWIP9(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "unwrapWIP9(uint256,address)"(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    WIP9(overrides?: CallOverrides): Promise<BigNumber>;

    "WIP9()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    initFlash(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initFlash((address,address,uint24,uint256,uint256,uint24,uint24))"(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    refundIP(overrides?: PayableOverrides): Promise<BigNumber>;

    "refundIP()"(overrides?: PayableOverrides): Promise<BigNumber>;

    storyHuntV3FlashCallback(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "storyHuntV3FlashCallback(uint256,uint256,bytes)"(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    "swapRouter()"(overrides?: CallOverrides): Promise<BigNumber>;

    sweepToken(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "sweepToken(address,uint256,address)"(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    unwrapWIP9(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "unwrapWIP9(uint256,address)"(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WIP9(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WIP9()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initFlash(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initFlash((address,address,uint24,uint256,uint256,uint24,uint24))"(
      params: {
        token0: string;
        token1: string;
        fee1: BigNumberish;
        amount0: BigNumberish;
        amount1: BigNumberish;
        fee2: BigNumberish;
        fee3: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    refundIP(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "refundIP()"(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    storyHuntV3FlashCallback(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "storyHuntV3FlashCallback(uint256,uint256,bytes)"(
      fee0: BigNumberish,
      fee1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "swapRouter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sweepToken(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "sweepToken(address,uint256,address)"(
      token: string,
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    unwrapWIP9(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "unwrapWIP9(uint256,address)"(
      amountMinimum: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
